### ISSUE TITLE
No head model for null gender

### ISSUE THREAD

**Issue by AuntieLumb** [SirRandoo/non-binary-pawns#1] opened 2021-08-30 19:17 UTC
Love this mod ty for publishing n keeping it up to date :) 
i just noticed though that when you set a pawns gender to none, its head disappears. in character editor i can see one option for a head, the option the pawn had set before switching gender. 
was wondering if it'd be possible to set the none gender to be able to use just, any head def available?

**Comment by AuntieLumb** [comment] 2021-08-30 19:25
also breaks animations looks like :(

**Comment by SirRandoo** [comment] 2021-08-30 19:43
Thanks for the report! One of the eventual goals of the mod is to allow genderless pawns to use whatever hair def, body def, and head def the player wanted, but it was put on hold to see how stable RimWorld (and mods) were with a pawn like that existing. It's also interesting to know that the head model disappeared. Do you happen to know what they were doing prior to this, and can you describe which animation(s) are broken?

**Comment by AuntieLumb** [comment] 2021-08-30 20:05
![image](https://user-images.githubusercontent.com/89806627/131398168-aed674e8-56b2-45a8-9f7f-485a637ceb72.png)
it looks like it takes off the head options, normally like, narrow pointy or average wide, and also removes the pawns adulthood backstory. these are still broken if i change the pawns gender back to male, so i suspect when you assign gender.Male that's not how the game sees gender? maybe idk im not a programmre

**Comment by AuntieLumb** [comment] 2021-08-30 20:08
no i take that back, the proper gender face and backstories can be assigned when changed back to male or female my bad

**Comment by AuntieLumb** [comment] 2021-08-30 20:52
okay so it seeeems like this is more like just how this gender exists in the code, since the game, and mods all constantly ask for gender for relationship stuff, pretty much all of that breaks when the gender is None cuz they're just doing if male then, else female then, and not allowing for none, sometimes null, but i doubt that would be a nice solution for here :(

**Comment by SirRandoo** [comment] 2021-08-30 21:03
Yup, `None` is a gender option used by the game for pawns that don't have genders. I'm not entirely sure which mod is doing what you're experiencing, but I couldn't reproduce the problems you were having in character editor.
![image](https://user-images.githubusercontent.com/8146689/131404802-fad4ed8c-3c5c-4a45-a2a0-4c4993c7d01e.png)

Nor was I able to reproduce the relationship problems genderless pawns had. Prior to uploading the mod, I did let the game run for several hours to see how pawns would interact with each other, and they were able to form relationships. I can't recall the specifics, but they were able to find a lover when I last checked up on them.

If you could provide your mod list, or a your log around the time this happens, that'd might help figure out what might be happening.

**Comment by SirRandoo** [comment] 2021-11-29 20:54
Seems this is caused by Humanoid Alien Races trying to update the pawn's graphic when their overall health changes. Should have a fix within the week, as well as the foundation for other features.

**Comment by SirRandoo** [comment] 2021-12-03 16:57
Fixed in f70fc1862eb34e227a564d7da98332caf8480eb2

**Closed as completed by SirRandoo** 2021-12-03 16:57 UTC
Labels: bug
